### ISSUE TITLE
Initialize delay

### ISSUE THREAD

**Issue by laszlokovacs25** [sparkfun/SparkFun_SGP40_Arduino_Library#2]
Hi all, looks like there is a little issue during mySensor.begin();

I've built a couple of pcbs designed with sgp40 and I use this library. First few pcbs were ok but later with a new batch of SGP40 I had issue during sensor.begin(). After few hours tests I figured out the problem was the delay in the SparkFun_SGP40_Arduino_Library.cpp file.
The begin loop calls the measureTest() loop. (line 74)
In the measureTest() loop, at line77 (  _i2cPort->write(sgp40_measure_test, 2); ) the request is correct according to the datasheets (page 12) (table 8), where all the datasheet says after request need to wait at least 250ms.
https://cdn.sparkfun.com/assets/e/6/2/6/d/Sensirion_Gas_Sensors_SGP40_Datasheet.pdf 
https://docs.rs-online.com/1956/A700000007055193.pdf
https://cdn-learn.adafruit.com/assets/assets/000/097/511/original/Sensirion_Gas-Sensors_SGP40_Datasheet.pdf?1607381770
SparkFun_SGP40_Arduino_Library.cpp line 91 ( delay(250); )
This was working until the new batch.

I guess, the manufacturer of the SGP40 changed something because the delay must be increased to 300ms with the new sensors and it works with 300 in my case.
Because of this issue, I opened the original sensirion datasheet to compare the data and the new datasheet says 300-320ms.
(page 12)
https://sensirion.com/media/documents/296373BB/61644B0A/Sensirion_Gas_Sensors_Datasheet_SGP40.pdf

All distributor use the old datasheet fom July 2020 but the new sensirion datasheet is from Sept 2021.

please update the library.

Can be other changes but I haven't met with them.

Thx

**Comment by PaulZC** [comment]
Thank you Laszlo (@laszlokovacs25 ),

I will update the library now.

Best wishes,
Paul

**Comment by PaulZC** [comment]
Fixed in v1.0.3 - thanks!

**Comment by laszlokovacs25** [comment]
This was quick, thx.
Just one thing, the last page of the new sensirion datasheet shows the changes between the previous and the new version.

**Comment by PaulZC** [comment]
Indeed - thanks!

The new ```get_serial_number``` command could be useful... I will think about adding support for that.

Best wishes,
Paul
